FROM osrf/ros:humble-desktop
ENV ROS_DISTRO humble

# install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        git \
        build-essential \
        cmake \
        byobu \
        vim \
        libeigen3-dev \
        libepoxy-dev \
        python3-colcon-common-extensions \
        libopencv-dev \
        ros-$ROS_DISTRO-vision-opencv \
        ros-$ROS_DISTRO-message-filters && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

WORKDIR /root

# build pangolin
WORKDIR /home/thirdparty
RUN git clone https://github.com/stevenlovegrove/Pangolin.git && \
    cd Pangolin && \
    mkdir build && cd build && \
    cmake .. && \
    make -j && \
    make install

# build ORB SLAM3
RUN git clone https://github.com/jnskkmhr/ORB-SLAM3-STEREO-FIXED.git ORB_SLAM3
RUN cd ORB_SLAM3 && \
chmod +x build.sh && \
./build.sh
# Issue: otherwise, you will have Sophus include errors
RUN cd ORB_SLAM3/Thirdparty/Sophus/build && make install

# Install librealsense sdk
RUN mkdir -p /etc/apt/keyrings && curl -sSf https://librealsense.intel.com/Debian/librealsense.pgp | sudo tee /etc/apt/keyrings/librealsense.pgp > /dev/null
RUN apt-get update && apt-get install apt-transport-https
RUN echo "deb [signed-by=/etc/apt/keyrings/librealsense.pgp] https://librealsense.intel.com/Debian/apt-repo `lsb_release -cs` main" | tee /etc/apt/sources.list.d/librealsense.list
RUN apt-get update && apt-get install librealsense2-dkms librealsense2-utils librealsense2-dev librealsense2-dbg
RUN apt-get install ros-${ROS_DISTRO}-realsense2-*

RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /root/.bashrc
WORKDIR /home/ros2_ws

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]