FROM osrf/ros:foxy-desktop
ENV ROS_DISTRO foxy

# install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        git \
        build-essential \
        cmake \
        byobu \
        vim \
        wget \
        unzip \
        libeigen3-dev \
        python3-colcon-common-extensions \
        libopencv-dev \
        ros-$ROS_DISTRO-vision-opencv \
        ros-$ROS_DISTRO-message-filters && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# build pangolin
WORKDIR /home/thirdparty
RUN git clone https://github.com/stevenlovegrove/Pangolin.git && \
    cd Pangolin && \
    apt-get update && \
    yes | ./scripts/install_prerequisites.sh required && \
    cmake -B build && \
    cmake --build build

# build ORB SLAM3
RUN git clone https://github.com/jnskkmhr/ORB-SLAM3-STEREO-FIXED.git ORB_SLAM3
RUN cd ORB_SLAM3 && \
git pull origin && \
chmod +x build.sh && \
./build.sh
# Issue: otherwise, you will have Sophus include errors
RUN cd ORB_SLAM3/Thirdparty/Sophus/build && make install

# Install librealsense sdk
RUN mkdir -p /etc/apt/keyrings && curl -sSf https://librealsense.intel.com/Debian/librealsense.pgp | sudo tee /etc/apt/keyrings/librealsense.pgp > /dev/null
RUN apt-get update && apt-get install -y apt-transport-https
RUN echo "deb [signed-by=/etc/apt/keyrings/librealsense.pgp] https://librealsense.intel.com/Debian/apt-repo `lsb_release -cs` main" | tee /etc/apt/sources.list.d/librealsense.list
RUN apt-get update && apt-get install -y librealsense2-dkms librealsense2-utils librealsense2-dev librealsense2-dbg

# build realsense ros2 from source
WORKDIR /home/thirdparty/ros2_ws/src
RUN git clone https://github.com/IntelRealSense/realsense-ros.git
WORKDIR /home/thirdparty/ros2_ws
RUN rosdep install -i --from-path src --rosdistro $ROS_DISTRO --skip-keys=librealsense2 -y
RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.sh && \
colcon build --symlink-install --packages-select \
realsense2_camera realsense2_camera_msgs \
realsense2_description"

WORKDIR /home/ros2_ws
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /root/.bashrc
RUN echo "source /home/thirdparty/ros2_ws/install/setup.bash" >> /root/.bashrc

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]