FROM osrf/ros:humble-desktop
ENV ROS_DISTRO humble

# install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        git \
        build-essential \
        cmake \
        byobu \
        vim \
        libeigen3-dev \
        python3-colcon-common-extensions \
        libopencv-dev \
        ros-$ROS_DISTRO-vision-opencv \
        ros-$ROS_DISTRO-message-filters && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# build pangolin
WORKDIR /opt/thirdparty
RUN git clone https://github.com/stevenlovegrove/Pangolin.git && \
    cd Pangolin && \
    apt-get update && \
    yes | ./scripts/install_prerequisites.sh required && \
    cmake -B build && \
    cmake --build build

# build ORB SLAM3
RUN git clone https://github.com/jnskkmhr/ORB-SLAM3-STEREO-FIXED.git ORB_SLAM3
RUN cd ORB_SLAM3 && \
chmod +x build.sh && \
./build.sh
# Issue: otherwise, you will have Sophus include errors
RUN cd ORB_SLAM3/Thirdparty/Sophus/build && make install

# Install librealsense sdk
RUN mkdir -p /etc/apt/keyrings && curl -sSf https://librealsense.intel.com/Debian/librealsense.pgp | sudo tee /etc/apt/keyrings/librealsense.pgp > /dev/null
RUN apt-get update && apt-get install -y apt-transport-https
RUN echo "deb [signed-by=/etc/apt/keyrings/librealsense.pgp] https://librealsense.intel.com/Debian/apt-repo `lsb_release -cs` main" | tee /etc/apt/sources.list.d/librealsense.list
RUN apt-get update && apt-get install -y librealsense2-dkms librealsense2-utils librealsense2-dev librealsense2-dbg

# Install octomap
WORKDIR /opt/thirdparty
RUN apt-get install wget unzip 
RUN wget https://github.com/OctoMap/octomap/archive/refs/tags/v1.10.0.zip
RUN unzip v1.10.0.zip && rm v1.10.0.zip && mv octomap-1.10.0 octomap
RUN cd octomap && \
mkdir build && \
cd build && \
cmake .. && \
make

WORKDIR /opt/thirdparty/ros2_ws/src
RUN git clone https://github.com/IntelRealSense/realsense-ros.git
RUN git clone https://github.com/iKrishneel/octomap_server2.git && vcs import . < deps.repos
WORKDIR /opt/thirdparty/ros2_ws
RUN rosdep install -i --from-path src --rosdistro $ROS_DISTRO --skip-keys=librealsense2 -y
RUN --symlink-install --packages-select \
realsense2_camera realsense2_camera_msgs realsense2_description octomap_msgs octomap_server2

WORKDIR /home/ros2_ws
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /root/.bashrc
RUN echo "source /opt/thirdparty/ros2_ws/install/setup.bash" >> /root/.bashrc

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]