orbslam3:
  ros__parameters:
    color_topic: "/camera/color/resize/image_raw"
    depth_topic: "/camera/depth/resize/image_raw"

    world_frame: "map"
    odom_frame: "odom"
    camera_frame: "vo"
    local_mapping: true